"""create game in model.py

Revision ID: e65f8e47359c
Revises: 9bcd02936d98
Create Date: 2024-03-26 00:44:42.193966

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e65f8e47359c'
down_revision = '9bcd02936d98'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
